version: '3.3'
services:
  jatDatabase:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: jatdb
      MYSQL_ROOT_PASSWORD: kirk824
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sharedDatabase

  jobdlink:
    image: jobdlinkdocker:latest
    ports:
      - "3001:3001"
    environment:
      SECRET_KEY: letskeeparandomsecretkeyforjwttoken
      SESSION_SECRET: mustbeasecret
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      MYSQL_DATABASE: jatdb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: kirk824
      MYSQL_HOST: jatDatabase
      PORT: 3001
      NODE_ENV: production
      REACT_APP_NODE_ENV: production
      REACT_APP_LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
    depends_on:
      - jatDatabase
    volumes:
      - ./uploads:/app/uploads
    networks:
      - sharedDatabase

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434" # Expose the port if you need external access
    networks:
      - sharedDatabase

volumes:
  mysql_data:

networks:
  sharedDatabase:
    external: true   # Reference to the external network