POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "deepakr",
    "password": "123456789",
    "email": "deep@gmail.com"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "bhandarideepakdev@gmail.com2",
    "password": "12345678"
}

###

POST http://localhost:3001/jobs/
Content-Type: application/json

{
    "jobTitle": "Frontend Developer",
    "jobUrl": "https://www.google.com",
    "company": "Google",
    "status": "Applied",
    "user_id": 1,
    "location": "NewYork",
    "username": "deepakr",
    "private": false,
    "description": "ömflsmdlkfm",
    "caption": "hgkadjgadgs"
}

###

GET http://localhost:3001/jobs/
# Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImlhdCI6MTcxNzQzOTE3MCwiZXhwIjoxNzE3NTI1NTcwfQ.8FQIr4j4iLlAWfdWrEkBdQSgKtdrUYUiXBBP6Imbm_8


###

POST http://localhost:3001/jobLike/
Content-Type: application/json

{
    "job_id": 9,
    "user_id": 4
}
###

POST http://localhost:3001/jobComment/
Content-Type: application/json

{
    "job_id": 9,
    "user_id": 4,
    "comment": "This is a comment"
}

###

DELETE http://localhost:3001/jobComment/9/4
Content-Type: application/json

###
//Update Comment
PUT http://localhost:3001/jobComment/2
Content-Type: application/json

{
    "comment": "This is a new comment"
}

###

GET http://localhost:3001/jobComment/2


###

DELETE http://localhost:3001/jobComment/61/21


###
PUT http://localhost:3001/jobs/3
Content-Type: application/json

{
    "jobTitle": "Frontend Developer",
    "jobUrl": "https://www.google.com",
    "company": "Google",
    "status": "Applied",
    "user_id": 1,
    "location": "NewYork",
    "username": "deepakr",
    "description": "ömflsmdlkfm",
    "caption": "hgkadjgadgs",
    "id": 3,
    "private": false
}
