name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build React App
        working-directory: ./jatfront
        run: |
          npm install
          npm run build

      - name: Build Docker Images
        run: |
          # Build Express Docker Image
          docker build -t jobdlinkdocker:latest ./express
         

      - name: Save Docker Images
        run: |
          docker save jobdlinkdocker:latest -o jobdlinkdocker.tar
         

      - name: Change permissions for Docker Image files
        run: |
          chmod 755 jobdlinkdocker.tar
         

      - name: Transfer Docker Image File to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 22
          source: |
            jobdlinkdocker.tar
            
          target: /var/www/jobd.link
          key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Load Docker Images
            docker load -i /var/www/jobd.link/jobdlinkdocker.tar
           

            # Change directory to where docker-compose.yml is located
            cd /var/www/jobd.link/

            # Stop and remove old containers if they exist
            docker-compose down

            # Start new containers with the updated images
            docker-compose up -d
